In [1]:
import numpy as np
import pandas as pd

In [2]:
scada_err_19 = pd.read_csv("/Users/Jake/Google Drive/renewablesAIProject/Python_code/scada_err_19.csv") 

In [4]:
scada_cleaned =  pd.read_csv("/Users/Jake/Google Drive/renewablesAIProject/Python_code/scada_err_19_whole.csv") 
scada_cleaned  = scada_cleaned .drop(['Unnamed: 0'], axis=1)
scada_err_19  = scada_err_19 .drop(['Unnamed: 0'], axis=1)

In [5]:
from sklearn.decomposition import PCA
X = scada_cleaned.drop('Error_Code', axis=1) 
X = X.drop('datetime', axis=1) 
X = X.drop('inverter', axis=1) 
pca = PCA(n_components=20, whiten=True).fit(X)
print(sum(pca.explained_variance_ratio_))

0.999999999995


In [6]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
X = scada_cleaned.drop('Error_Code', axis=1) 
X = X.drop('datetime', axis=1) 
X = X.drop('inverter', axis=1) 

z_scaler = StandardScaler()
z_data = z_scaler.fit_transform(X)
pca_trafo = PCA().fit(z_data);

plt.semilogy(pca_trafo.explained_variance_ratio_, '--o');
plt.semilogy(pca_trafo.explained_variance_ratio_.cumsum(), '--o');

In [7]:
plt.show()

In [58]:
import numpy as np
import pandas as pd
scada_cleaned = pd.read_csv("/Users/Jake/Google Drive/renewablesAIProject/Python_code/scada_err_19.csv", parse_dates=['datetime'], index_col=['datetime'])

inverter_col = scada_cleaned[scada_cleaned.columns[1]]
inverter_col = pd.DataFrame(inverter_col)


i1 = inverter_col.loc[inverter_col['inverter'] == 1]
i2 = inverter_col.loc[inverter_col['inverter'] == 2]
i3 = inverter_col.loc[inverter_col['inverter'] == 3]
i4 = inverter_col.loc[inverter_col['inverter'] == 4]
i5 = inverter_col.loc[inverter_col['inverter'] == 5]
i6 = inverter_col.loc[inverter_col['inverter'] == 6]

i1 = i1.resample("1H").apply({'inverter': np.max})
i2 = i2.resample("1H").apply({'inverter': np.max})
i3 = i3.resample("1H").apply({'inverter': np.max})
i4 = i4.resample("1H").apply({'inverter': np.max})
i5 = i5.resample("1H").apply({'inverter': np.max})
i6 = i6.resample("1H").apply({'inverter': np.max})
i = [i1, i2, i3, i4, i5, i6]
i = pd.concat(i)

scada_cleaned.drop(scada_cleaned.columns[[0, 21]], axis=1, inplace=True)

inv1 = scada_cleaned.loc[scada_cleaned['inverter'] == 1]
inv2 = scada_cleaned.loc[scada_cleaned['inverter'] == 2]
inv3 = scada_cleaned.loc[scada_cleaned['inverter'] == 3]
inv4 = scada_cleaned.loc[scada_cleaned['inverter'] == 4]
inv5 = scada_cleaned.loc[scada_cleaned['inverter'] == 5]
inv6 = scada_cleaned.loc[scada_cleaned['inverter'] == 6]

inv1 = inv1.resample("1H").apply(['mean', np.min, np.max])
inv1.drop(inv1.columns[[0, 1, 2]], axis=1, inplace=True)

inv2 = inv2.resample("1H").apply(['mean', np.min, np.max])
inv2.drop(inv2.columns[[0, 1, 2]], axis=1, inplace=True)

inv3 = inv3.resample("1H").apply(['mean', np.min, np.max])
inv3.drop(inv3.columns[[0, 1, 2]], axis=1, inplace=True)

inv4 = inv4.resample("1H").apply(['mean', np.min, np.max])
inv4.drop(inv4.columns[[0, 1, 2]], axis=1, inplace=True)

inv5 = inv5.resample("1H").apply(['mean', np.min, np.max])
inv5.drop(inv5.columns[[0, 1, 2]], axis=1, inplace=True)

inv6 = inv6.resample("1H").apply(['mean', np.min, np.max])
inv6.drop(inv6.columns[[0, 1, 2]], axis=1, inplace=True)

inv = [inv1, inv2, inv3, inv4, inv5, inv6]
scada_cleaned = pd.concat(inv)
scada_cleaned = scada_cleaned.reset_index()
i = i.reset_index()
scada_cleaned = i.join(scada_cleaned)
scada_cleaned.drop(scada_cleaned.columns[[2]], axis=1, inplace=True)

/Users/Jake/anaconda3/lib/python3.6/site-packages/pandas/core/reshape/merge.py:551: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)


In [59]:
scada_cleaned.head()

datetime  inverter  (WS_Ambient_temperature, mean)  \
0 2016-10-12 00:00:00       1.0                        9.204997   
1 2016-10-12 01:00:00       1.0                       10.118335   
2 2016-10-12 02:00:00       1.0                       10.028335   
3 2016-10-12 03:00:00       1.0                       10.003334   
4 2016-10-12 04:00:00       1.0                       10.105000   

   (WS_Ambient_temperature, amin)  (WS_Ambient_temperature, amax)  \
0                        8.733326                        9.799999   
1                       10.059999                       10.180006   
2                        9.906666                       10.193339   
3                        9.473332                       10.266660   
4                        9.600003                       10.506667   

   (WS_Barometric_Pressure, mean)  (WS_Barometric_Pressure, amin)  \
0                     1010.183325                       1010.1339   
1                     1010.204825                       1010.1732   
2                     1010.028200                       1009.8799   
3                     1009.661850                       1009.5735   
4                     1009.473275                       1009.4396   

   (WS_Barometric_Pressure, amax)  (WS_Relative_Humidity, mean)  \
0                       1010.2266                     92.969995   
1                       1010.2264                     91.821675   
2                       1010.1667                     93.233320   
3                       1009.7600                     93.348330   
4                       1009.5203                     93.309980   

   (WS_Relative_Humidity, amin)         ...          (module_2h_cum, amax)  \
0                      91.68665         ...                            0.0   
1                      91.39333         ...                            0.0   
2                      92.81332         ...                            0.0   
3                      93.13998         ...                            0.0   
4                      92.23334         ...                            0.0   

   (Inv_efficiency_24h_avg, mean)  (Inv_efficiency_24h_avg, amin)  \
0                       98.160591                       98.160591   
1                       98.160591                       98.160591   
2                       98.160591                       98.160591   
3                       98.160591                       98.160591   
4                       98.160591                       98.160591   

   (Inv_efficiency_24h_avg, amax)  (Mean_array_efficiency_24h_avg, mean)  \
0                       98.160591                              15.005723   
1                       98.160591                              15.005723   
2                       98.160591                              15.005723   
3                       98.160591                              15.005723   
4                       98.160591                              15.005723   

   (Mean_array_efficiency_24h_avg, amin)  \
0                              15.005723   
1                              15.005723   
2                              15.005723   
3                              15.005723   
4                              15.005723   

   (Mean_array_efficiency_24h_avg, amax)  (DC_AC_diff, mean)  \
0                              15.005723                 0.0   
1                              15.005723                 0.0   
2                              15.005723                 0.0   
3                              15.005723                 0.0   
4                              15.005723                 0.0   

   (DC_AC_diff, amin)  (DC_AC_diff, amax)  
0                 0.0                 0.0  
1                 0.0                 0.0  
2                 0.0                 0.0  
3                 0.0                 0.0  
4                 0.0                 0.0  

[5 rows x 59 columns]

In [60]:
err_19 = pd.read_csv("/Users/Jake/Google Drive/renewablesAIProject/Python_code/EC_19.csv", parse_dates=['datetime'], index_col=['datetime'])
err_19  = err_19.drop(['Unnamed: 0'], axis=1)

e1 = err_19.loc[err_19['inverter'] == 1]
e2 = err_19.loc[err_19['inverter'] == 2]
e3 = err_19.loc[err_19['inverter'] == 3]
e4 = err_19.loc[err_19['inverter'] == 4]
e5 = err_19.loc[err_19['inverter'] == 5]
e6 = err_19.loc[err_19['inverter'] == 6]

e1 = e1.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e2 = e2.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e3 = e3.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e4 = e4.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e5 = e5.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e6 = e6.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
es = [e1, e2, e3, e4, e5, e6]

err_19 = pd.concat(es)
err_19 = err_19[np.isfinite(err_19['inverter'])]


scada_cleaned = scada_cleaned.reset_index()
err_19 = err_19.reset_index()
scada_err_19 = pd.merge(scada_cleaned, err_19, how='outer', on=['datetime', 'inverter'])

scada_err_19['Error_Code'] = scada_err_19['Error_Code'].fillna(0)
scada_err_19['Modules_affected'] = scada_err_19['Modules_affected'].fillna(0)
scada_err_19['Error_Code'] = scada_err_19['Error_Code'].shift(-1)
scada_err_19 = scada_err_19.rename(columns={'Error_Code': 'Err_Code_nxt_hour'})

In [61]:
from sklearn.cross_validation import train_test_split
import random
scada_err_19 = scada_err_19.dropna()
scada_err_19.drop('datetime', axis=1, inplace=True)
X = scada_err_19.drop('Err_Code_nxt_hour', axis=1) 
y = scada_err_19['Err_Code_nxt_hour']
random.seed(40)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y)

## Decision Tree Model

In [62]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix 
import random 
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=20, min_samples_leaf=5)

clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
                               max_depth=20, min_samples_leaf=5)
clf_gini.fit(X_train, y_train) 
clf_entropy.fit(X_train, y_train) 
y_pred = clf_gini.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))
y_pred = clf_entropy.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[21533    17]
 [   32    51]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00     21550
        1.0       0.75      0.61      0.68        83

avg / total       1.00      1.00      1.00     21633

[[21526    24]
 [   35    48]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00     21550
        1.0       0.67      0.58      0.62        83

avg / total       1.00      1.00      1.00     21633



## Random Forest Model

In [24]:
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train)
predictions = rf.predict(X_test)
predictions = pd.DataFrame(predictions)
predictions[predictions.columns[0]]= predictions[predictions.columns[0]].round()
print(confusion_matrix(y_test, predictions))  
print(classification_report(y_test, predictions))

KeyboardInterrupt: 

## KNN Classifier Model

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
predictions = knn.predict(X_test)
print(confusion_matrix(y_test, predictions))  
print(classification_report(y_test, predictions))

[[21541     9]
 [   54    29]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00     21550
        1.0       0.76      0.35      0.48        83

avg / total       1.00      1.00      1.00     21633



## XGBoost Model

In [63]:
import xgboost as xgb
from xgboost import XGBClassifier
from xgboost import plot_importance
import matplotlib.pyplot as plt

XGBmodel = XGBClassifier()
XGBmodel.fit(X_train,y_train)
predictions = XGBmodel.predict(X_test) 
print(confusion_matrix(y_test, predictions))  
print(classification_report(y_test, predictions))

xgb.plot_importance(XGBmodel)

[[21546     4]
 [   29    54]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00     21550
        1.0       0.93      0.65      0.77        83

avg / total       1.00      1.00      1.00     21633



## Optimised XGBoost

In [ ]:
from sklearn.cross_validation import *
from sklearn.grid_search import GridSearchCV
cv_params = {'max_depth': [3,5,7], 'min_child_weight': [1,3,5]}
ind_params = {'learning_rate': 0.1, 'n_estimators': 1000, 'seed':0, 'subsample': 0.8, 'colsample_bytree': 0.8, 
             'objective': 'binary:logistic'}

optimized_GBM = GridSearchCV(XGBClassifier(**ind_params), 
                            cv_params, 
                             scoring = 'recall', cv = 5, n_jobs = -1) 

optimized_GBM .fit(X_train,y_train)

# High Feature Data set

## Feature Engineering 

In [97]:
import numpy as np
import pandas as pd
scada_cleaned2 = pd.read_csv("/Users/Jake/Google Drive/renewablesAIProject/Python_code/scada_err_19_whole.csv", parse_dates=['datetime'], index_col=['datetime'])

#scada_cleaned.drop(scada_cleaned.columns[[44, 45, 46]], axis=1, inplace=True)

inverter_col = scada_cleaned2[scada_cleaned2.columns[1]]
inverter_col = pd.DataFrame(inverter_col)


i1 = inverter_col.loc[inverter_col['inverter'] == 1]
i2 = inverter_col.loc[inverter_col['inverter'] == 2]
i3 = inverter_col.loc[inverter_col['inverter'] == 3]
i4 = inverter_col.loc[inverter_col['inverter'] == 4]
i5 = inverter_col.loc[inverter_col['inverter'] == 5]
i6 = inverter_col.loc[inverter_col['inverter'] == 6]

i1 = i1.resample("1H").apply({'inverter': np.max})
i2 = i2.resample("1H").apply({'inverter': np.max})
i3 = i3.resample("1H").apply({'inverter': np.max})
i4 = i4.resample("1H").apply({'inverter': np.max})
i5 = i5.resample("1H").apply({'inverter': np.max})
i6 = i6.resample("1H").apply({'inverter': np.max})
i = [i1, i2, i3, i4, i5, i6]
i = pd.concat(i)

scada_cleaned2.drop(scada_cleaned2.columns[[0, 43, 44, 45]], axis=1, inplace=True)


inv1 = scada_cleaned2.loc[scada_cleaned2['inverter'] == 1]
inv2 = scada_cleaned2.loc[scada_cleaned2['inverter'] == 2]
inv3 = scada_cleaned2.loc[scada_cleaned2['inverter'] == 3]
inv4 = scada_cleaned2.loc[scada_cleaned2['inverter'] == 4]
inv5 = scada_cleaned2.loc[scada_cleaned2['inverter'] == 5]
inv6 = scada_cleaned2.loc[scada_cleaned2['inverter'] == 6]

inv1 = inv1.resample("1H").apply(['mean', np.min, np.max])
inv1.drop(inv1.columns[[0, 1, 2]], axis=1, inplace=True)

inv2 = inv2.resample("1H").apply(['mean', np.min, np.max])
inv2.drop(inv2.columns[[0, 1, 2]], axis=1, inplace=True)

inv3 = inv3.resample("1H").apply(['mean', np.min, np.max])
inv3.drop(inv3.columns[[0, 1, 2]], axis=1, inplace=True)

inv4 = inv4.resample("1H").apply(['mean', np.min, np.max])
inv4.drop(inv4.columns[[0, 1, 2]], axis=1, inplace=True)

inv5 = inv5.resample("1H").apply(['mean', np.min, np.max])
inv5.drop(inv5.columns[[0, 1, 2]], axis=1, inplace=True)

inv6 = inv6.resample("1H").apply(['mean', np.min, np.max])
inv6.drop(inv6.columns[[0, 1, 2]], axis=1, inplace=True)

inv = [inv1, inv2, inv3, inv4, inv5, inv6]
scada_cleaned2 = pd.concat(inv)
scada_cleaned2 = scada_cleaned2.reset_index()
i = i.reset_index()
scada_cleaned2 = i.join(scada_cleaned2)
scada_cleaned2.drop(scada_cleaned2.columns[[0,1]], axis=1, inplace=True)

/Users/Jake/anaconda3/lib/python3.6/site-packages/pandas/core/reshape/merge.py:551: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)


In [98]:
scada_cleaned2.head()

(datetime, )  (WS_Ambient_temperature, mean)  \
0 2016-10-12 00:00:00                        9.204997   
1 2016-10-12 01:00:00                       10.118335   
2 2016-10-12 02:00:00                       10.028335   
3 2016-10-12 03:00:00                       10.003334   
4 2016-10-12 04:00:00                       10.105000   

   (WS_Ambient_temperature, amin)  (WS_Ambient_temperature, amax)  \
0                        8.733326                        9.799999   
1                       10.059999                       10.180006   
2                        9.906666                       10.193339   
3                        9.473332                       10.266660   
4                        9.600003                       10.506667   

   (WS_Barometric_Pressure, mean)  (WS_Barometric_Pressure, amin)  \
0                     1010.183325                       1010.1339   
1                     1010.204825                       1010.1732   
2                     1010.028200                       1009.8799   
3                     1009.661850                       1009.5735   
4                     1009.473275                       1009.4396   

   (WS_Barometric_Pressure, amax)  (WS_Precipitation, mean)  \
0                       1010.2266                      0.00   
1                       1010.2264                      0.01   
2                       1010.1667                      0.00   
3                       1009.7600                      0.00   
4                       1009.5203                      0.00   

   (WS_Precipitation, amin)  (WS_Precipitation, amax)         ...          \
0                       0.0                      0.00         ...           
1                       0.0                      0.04         ...           
2                       0.0                      0.00         ...           
3                       0.0                      0.00         ...           
4                       0.0                      0.00         ...           

   (Inv_efficiency_24h_avg, amax)  (Mean_array_efficiency_24h_avg, mean)  \
0                       98.160591                              15.005723   
1                       98.160591                              15.005723   
2                       98.160591                              15.005723   
3                       98.160591                              15.005723   
4                       98.160591                              15.005723   

   (Mean_array_efficiency_24h_avg, amin)  \
0                              15.005723   
1                              15.005723   
2                              15.005723   
3                              15.005723   
4                              15.005723   

   (Mean_array_efficiency_24h_avg, amax)  (Raw_PR_24h_avg, mean)  \
0                              15.005723               84.158966   
1                              15.005723               84.158966   
2                              15.005723               84.158966   
3                              15.005723               84.158966   
4                              15.005723               84.158966   

   (Raw_PR_24h_avg, amin)  (Raw_PR_24h_avg, amax)  (DC_AC_diff, mean)  \
0               84.158966               84.158966                 0.0   
1               84.158966               84.158966                 0.0   
2               84.158966               84.158966                 0.0   
3               84.158966               84.158966                 0.0   
4               84.158966               84.158966                 0.0   

   (DC_AC_diff, amin)  (DC_AC_diff, amax)  
0                 0.0                 0.0  
1                 0.0                 0.0  
2                 0.0                 0.0  
3                 0.0                 0.0  
4                 0.0                 0.0  

[5 rows x 136 columns]

In [99]:
err_19 = pd.read_csv("/Users/Jake/Google Drive/renewablesAIProject/Python_code/EC_19.csv", parse_dates=['datetime'], index_col=['datetime'])
err_19  = err_19.drop(['Unnamed: 0'], axis=1)

e1 = err_19.loc[err_19['inverter'] == 1]
e2 = err_19.loc[err_19['inverter'] == 2]
e3 = err_19.loc[err_19['inverter'] == 3]
e4 = err_19.loc[err_19['inverter'] == 4]
e5 = err_19.loc[err_19['inverter'] == 5]
e6 = err_19.loc[err_19['inverter'] == 6]

e1 = e1.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})

e2 = e2.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e3 = e3.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e4 = e4.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e5 = e5.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
e6 = e6.resample('1H').agg({'inverter': np.max, 'Error_Code': np.max, 'Modules_affected': np.sum})
es = [e1, e2, e3, e4, e5, e6]

err_19 = pd.concat(es)
err_19 = err_19[np.isfinite(err_19['inverter'])]


scada_cleaned2 = scada_cleaned2.reset_index()
err_19 = err_19.reset_index()
scada_err_19_big = pd.merge(scada_cleaned2, err_19, how='outer', on=['datetime', 'inverter'])

scada_err_19_big['Error_Code'] = scada_err_19_big['Error_Code'].fillna(0)
scada_err_19_big['Modules_affected'] = scada_err_19_big['Modules_affected'].fillna(0)
scada_err_19_big['Error_Code'] = scada_err_19_big['Error_Code'].shift(-1)
scada_err_19_big = scada_err_19_big.rename(columns={'Error_Code': 'Err_Code_nxt_hour'})
scada_err_19_big = scada_err_19_big.dropna()

KeyError: 'datetime'

In [91]:
scada_cleaned2 = scada_cleaned2.reset_index()
err_19 = err_19.reset_index()
scada_err_19_big = pd.merge(scada_cleaned2, err_19, how='outer', on=['datetime', 'inverter'])

scada_err_19_big['Error_Code'] = scada_err_19_big['Error_Code'].fillna(0)
scada_err_19_big['Modules_affected'] = scada_err_19_big['Modules_affected'].fillna(0)
scada_err_19_big['Error_Code'] = scada_err_19_big['Error_Code'].shift(-1)
scada_err_19_big = scada_err_19_big.rename(columns={'Error_Code': 'Err_Code_nxt_hour'})
scada_err_19_big = scada_err_19_big.dropna()

### Train, test split

In [92]:
scada_err_19_big.drop('datetime', axis=1, inplace=True)
X = scada_err_19_big.drop('Err_Code_nxt_hour', axis=1) 
y = scada_err_19_big['Err_Code_nxt_hour']
random.seed(0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y)

### Decision Tree Model for high feature data set

In [93]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=20, min_samples_leaf=5)

clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,
                               max_depth=20, min_samples_leaf=5)
clf_gini.fit(X_train, y_train) 
clf_entropy.fit(X_train, y_train) 
y_pred = clf_gini.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))
y_pred = clf_entropy.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[25 10]
 [ 7 41]]
             precision    recall  f1-score   support

        0.0       0.78      0.71      0.75        35
        1.0       0.80      0.85      0.83        48

avg / total       0.79      0.80      0.79        83

[[25 10]
 [ 7 41]]
             precision    recall  f1-score   support

        0.0       0.78      0.71      0.75        35
        1.0       0.80      0.85      0.83        48

avg / total       0.79      0.80      0.79        83



## XGBoost Model

In [76]:
from xgboost import XGBClassifier
from xgboost import plot_importance
import xgboost as xgb
import matplotlib.pyplot as plt
#%%
XGBmodel = XGBClassifier()
XGBmodel.fit(X_train,y_train)
predictions = XGBmodel.predict(X_test) 
print(confusion_matrix(y_test, predictions))  
print(classification_report(y_test, predictions))

xgb.plot_importance(XGBmodel)

[[29  6]
 [ 4 44]]
             precision    recall  f1-score   support

        0.0       0.88      0.83      0.85        35
        1.0       0.88      0.92      0.90        48

avg / total       0.88      0.88      0.88        83



In [83]:
scada_err_19_big

level_0  index_x  inverter  (WS_Ambient_temperature, mean)  \
2579    2579.0   2579.0       1.0                        2.189999   
6017    6012.0   6012.0       1.0                       27.935834   
6018    6013.0   6013.0       1.0                       28.411670   
6019    6014.0   6014.0       1.0                       28.458334   
6042    6037.0   6037.0       1.0                       26.858332   
6043    6038.0   6038.0       1.0                       27.055839   
6067    6062.0   6062.0       1.0                       27.167500   
13317  13307.0  13307.0       1.0                       24.184168   
13318  13308.0  13308.0       1.0                       25.306663   
13319  13309.0  13309.0       1.0                       26.038335   
13320  13310.0  13310.0       1.0                       26.391665   
13704  13694.0  13694.0       1.0                       20.506663   
13725  13715.0  13715.0       1.0                       21.266662   
13727  13717.0  13717.0       1.0                       22.365835   
13728  13718.0  13718.0       1.0                       22.830003   
13751  13741.0  13741.0       1.0                       25.281668   
13752  13742.0  13742.0       1.0                       25.591662   
13773  13763.0  13763.0       1.0                       23.847502   
13774  13764.0  13764.0       1.0                       24.694997   
13775  13765.0  13765.0       1.0                       24.922668   
27740  27732.0  27732.0       2.0                       25.306663   
27741  27733.0  27733.0       2.0                       26.038335   
27742  27734.0  27734.0       2.0                       26.391665   
28173  28165.0  28165.0       2.0                       25.281668   
28174  28166.0  28166.0       2.0                       25.591662   
28196  28188.0  28188.0       2.0                       24.694997   
31435  31427.0  31427.0       3.0                        2.189999   
34867  34860.0  34860.0       3.0                       27.935835   
34868  34861.0  34861.0       3.0                       28.411670   
34869  34862.0  34862.0       3.0                       28.458335   
...        ...      ...       ...                             ...   
85500  85500.0  85500.0       6.0                       21.939170   
85501  85501.0  85501.0       6.0                       22.298676   
85502  85502.0  85502.0       6.0                       22.431663   
85503  85503.0  85503.0       6.0                       22.030830   
85812  85812.0  85812.0       6.0                       19.502500   
85813  85813.0  85813.0       6.0                       20.220840   
85814  85814.0  85814.0       6.0                       20.510662   
85815  85815.0  85815.0       6.0                       20.627498   
85835  85835.0  85835.0       6.0                       21.266662   
85836  85836.0  85836.0       6.0                       22.013996   
85837  85837.0  85837.0       6.0                       22.388666   
85838  85838.0  85838.0       6.0                       22.830003   
85839  85839.0  85839.0       6.0                       22.689996   
85840  85840.0  85840.0       6.0                       22.522503   
85858  85858.0  85858.0       6.0                       21.984167   
85859  85859.0  85859.0       6.0                       23.390006   
85860  85860.0  85860.0       6.0                       24.539443   
85861  85861.0  85861.0       6.0                       25.269334   
85862  85862.0  85862.0       6.0                       25.585328   
85863  85863.0  85863.0       6.0                       25.346668   
85864  85864.0  85864.0       6.0                       24.191672   
85882  85882.0  85882.0       6.0                       23.182502   
85883  85883.0  85883.0       6.0                       23.847502   
85884  85884.0  85884.0       6.0                       24.633333   
85885  85885.0  85885.0       6.0                       24.912668   
85886  85886.0  85886.0       6.0                       24.416665   
86150